name: Lint

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    environment: Build
    env:
      NODE_ENV: development
      ENV_EXAMPLE: ${{ secrets.ENV_EXAMPLE }} # Add or modify secrets in GitHub -> Environments / Configure Build

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm ci
      - run: npm run lint
